 LOCALHOST ### GET http://localhost:8080/contacts
### GET http://localhost:8080/contacts/63c65f03dce6bebdf45d64f4
 ### GET http://localhost:8080/contacts/63c65f03dce6bebdf45d64f5 ### GET http://localhost:8080/63c65f03dce6bebdf45d64f6
 Production
 ### GET https://cse341-node-p.onrender.com/contacts
 ### GET https://cse341-node-p.onrender.com/contacts/63c65f03dce6bebdf45d64f4
 ### GET https://cse341-node-p.onrender.com/contacts/63c65f03dce6bebdf45d64f5
 ### GET https://cse341-node-p.onrender.com/contacts/63c65f03dce6bebdf45d64f6